name: deployment

on:
  push:
    branches: [ main ]
    paths: 'openmapflow/scripts'

jobs:
  profile_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openmapflow
        run: ./deploy.sh
